# Promise

- 비동기 결과를 전파하기 위한 CPS 방식의 콜백을 대신할 강력한 대안
- ECMA 2015의 일부고 Node v4 이후에서 기본적으로 사용이 가능했음

<br/>

# Promise란 무엇일까

- 비동기 작업의 최종적인 결과 또는 에러를 가지고있는 객체

<br/>

### Promise의 상태

- 대기중(pending) : 비동기 작업이 아직 완료되지 않은 상태
- 완료됨(fulfilled) : 비동기 작업이 성공적으로 끝났을때
- 실패함(rejected) : 비동기 작업이 에러와 함께 종료됬을때
- 결정된(settled) : 프로미스가 이행되거나 거부된 상태

<br/>

### CPS 방식과 차이점

```ts
// CPS
asyncOperation(
  (arg,
  (err, result) => {
    if (err) {
      // 에러처리
    }

    // 성공처리
  })
);

// Promise
asyncOperationPromise(arg)
  .then((result) => {
    // 성공처리
  })
  .catch((err) => {
    // 에러처리
  });
```

<br/>

### Promise 체인

- 3개의 체인 중 아무대서나 실패하면 catch 구문으로 넘어감
- 각 상위 체인에서 성공값에 대해서 하위 체인에서 사용이 가능함

```ts
asyncOperationPromise(arg)
  .then((result1) => {
    // 성공처리
  })
  .then((result2) => {
    // 성공처리
  })
  .then((result3) => {
    // 성공처리
  })
  .catch((err) => {
    // 체인의 에러처리를 담당
  });
```

<br/>

### Promise/A+ 와 thenable

- 과거엔 여러개의 Promise 구현이 존재했고 대부분이 서로 호환되지 않았음
- 이러한 한계를 극복하기 위해서 Promise/A+ 사양을 만들었음
- Promise API를 포함단 다른 구현들은 then() 함수가 있는 모든 객체를 thenable 이라는 객체로 간주함

<br/>

# Promise API

### Promise 생성

```ts
const promise = new Promise((resolve, reject) => {});
```

<br/>

### Promise.resolve(obj)

- 다른 Promise, thenable 또는 값에서 새로운 Promise를 생성
- Promise가 전달되면 해당 Promise가 있는 그대로 반환됨
- Thenable이 전달되면 해당 라이브러리의 Promise로 반환됨
- 값이 제공되면 해당 Promise가 이행됨

<br/>

### Promise.reject(err)

- err라는 이유로 실패하는 Promise를 만듬

<br/>

### Promise.all(iterable)

- iterable한 객체(promise, thenable, 값 든) 내부의 모든 프로미스가 이행되면 결과값을 담은 배열을 반환
- 하나라도 실패하면 해당 사유를 가지고 reject 됨

<br/>

### Promise.allSettled(iterable)

- Promise.all()과는 다르게 모든 프로미스가 이행되면 결과값을 담은 배열을 반환
- 실패와 성공에 대한 모든결과가 존재하고 값을 담은 value, 실패사유를 담은 reason이 존재함

```ts
const promises = [Promise.resolve(1), Promise.resolve(2), Promise.resolve(3), Promise.reject(new Error("error"))];

Promise.allSettled(promises).then((results) => {
  console.log(results);
});
```

```
[
  { status: 'fulfilled', value: 1 },
  { status: 'fulfilled', value: 2 },
  { status: 'fulfilled', value: 3 },
  {
    status: 'rejected',
    reason: Error: error
        at Object.<anonymous> (C:\Users\Dongwoo\study\node.js 디자인패턴 바이블\dist\app.js:2:94)
        at Module._compile (node:internal/modules/cjs/loader:1358:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
        at Module.load (node:internal/modules/cjs/loader:1208:32)
        at Module._load (node:internal/modules/cjs/loader:1024:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
        at node:internal/main/run_main_module:28:49
  }
]
```

<br/>

### Promise.race(iterable)

- 제일 먼저 결정된 Promise만 반환

<br/>

### Promise.then(onFulfilled, onRejected)

- Promise의 필수 함수
- 성공에 대한 콜백을 받음

<br/>

### Promise.catch(onRejected)

- Promise의 필수 함수
- 실패에 대한 콜백을 받음

<br/>

### Promise.finally()

- 인자를 받지 않으며 전달된 인자는 무시됨

<br/>

# Promise 생성
